In [15]:
from numba import double
from numba.decorators import jit, autojit

In [16]:
import numpy as np
X = np.random.random((1000, 3))

In [17]:
def pairwise_numpy(X):
    return np.sqrt(((X[:, None, :] - X) ** 2).sum(-1))
%timeit pairwise_numpy(X)

10 loops, best of 3: 60.5 ms per loop


In [18]:
def pairwise_python(X):
    M = X.shape[0]
    N = X.shape[1]
    D = np.empty((M, M), dtype=np.float)
    for i in range(M):
        for j in range(M):
            d = 0.0
            for k in range(N):
                tmp = X[i, k] - X[j, k]
                d += tmp * tmp
            D[i, j] = np.sqrt(d)
    return D
%timeit pairwise_python(X)

1 loop, best of 3: 3 s per loop


In [43]:
X = np.random.rand(5,5)
print X

[[ 0.3367932   0.96441858  0.85461035  0.39435689  0.63691402]
 [ 0.81746585  0.18936717  0.11661316  0.65636352  0.45151057]
 [ 0.50970685  0.06531693  0.67487305  0.6343447   0.07784398]
 [ 0.06346266  0.66800149  0.15749044  0.9801902   0.42761923]
 [ 0.43424915  0.24875261  0.6702811   0.23868991  0.17950963]]


In [42]:
Pos = X >= 0.5
Pos = X[Pos]
print Pos

[ 0.90446013  0.74309337  0.50517245  0.6264218   0.55087883  0.92037393
  0.67327584  0.89200658  0.65344218  0.93201473  0.58048061  0.70144016
  0.50171599  0.92396405]


In [45]:
print range(len(Pos))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


In [46]:
def pairwise_python_rand(X):
    M = X.shape[0]
    N = X.shape[1]
    Pos = X >= 0.5
    Pos = X[Pos]
    Neg = X < 0.5
    Neg = X[Neg]
    D = 0
    for j in range(len(Pos)):
        D += Pos[j]
        for k in range(len(Neg)):
            D += Neg[k]
    return D

%timeit pairwise_python_rand(X)

10000 loops, best of 3: 40.6 µs per loop


In [26]:
from numba import double
from numba.decorators import jit, autojit

pairwise_numba = autojit(pairwise_python)

%timeit pairwise_numba(X)

The slowest run took 34.72 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 3: 6.95 ms per loop


# Another example

In [28]:
from numba import jit
from numpy import arange

In [30]:
@jit
def sum2d(arr):
    M, N = arr.shape
    result = 0.0
    for i in range(M):
        for j in range(N):
            result += arr[i,j]
    return result

a = arange(9).reshape(3,3)
%timeit sum2d(a)
print sum2d(a)

The slowest run took 163143.91 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 611 ns per loop
36.0
